INSERT INTO drugs_form (name) VALUES
  ('PILLS'),
  ('GEL'),
  ('SYRUP'),
  ('DROPS'),
  ('SUPPOSITORIES'),
  ('SACHETS'),
  ('CREAM'),
  ('SPRAY'),
  ('OINTMENT'),
  ('LIQUID'),
  ('POWDER'),
  ('INJECTION'),
  ('BANDAGE'),
  ('INHALER'),
  ('PATCH'),
  ('SOLUTION'),
  ('OTHER');